### ISSUE TITLE
Settings->BeantStalk options->Status bar->Status Bar Options

### ISSUE THREAD

**Issue by ghost** [scotthartbti/android_frameworks_base#15] opened 2014-02-02 21:34 UTC
Hey Scott,

There seems to be a bug after the latest changes you made to this section. It is not possible to change the battery icon, change the clock and date settings.
Apart from that the ROM is by far the best for me :)

**Comment by scotthartbti** [comment] 2014-02-02 21:37
Thanks for the report.  Pretty sure I know what the issue is and should be
a quick fix

**Comment by scotthartbti** [comment] 2014-02-02 21:48
fixed with settings commit https://github.com/scotthartbti/android_packages_apps_Settings/commit/2eccabc79db8af44ae2d029d35d5d04123bb438f

**Comment by scotthartbti** [comment] 2014-02-02 23:11
Actually i reverted the status/navbar color option.  The way it was implemented caused the original issues and then changing what needed to be changed caused the feature not to work at all.  I wasnt originally happy with the overall feature implementation so i have just reverted the entire feature for now until i can take another look at it.  Either way, issue resolved.

**Closed as completed by scotthartbti** 2014-02-02 23:11 UTC
